"""Make runnable gateway scenarios for mcp-sim; they embed this installation's server id.

Two sources:

* mcp-sim's pantry scenarios, written for the direct server. ContextForge names a federated tool
  ``<gateway-slug>-<tool-with-dashes>`` (``find_product`` -> ``pantry-find-product``), so they do
  not match through the gateway. This rewrites tool names and globs, swaps the server block for
  the virtual server's MCP endpoint ('pantry-sim'), and leaves everything else (role, goal,
  expected outcome, observers) as it was.
* ``--recipe``: this repository's own scenarios (``scenarios/*.yaml``), which are gateway-only
  (they need the fetch tool) and already use ContextForge's tool names. Only the placeholder
  server id is filled in, with the 'pantry-recipes' virtual server's id; comments are kept.

Usage: make_scenarios.py <mcp-sim>/scenarios/pantry <pantry-sim server-id> [out-dir]
       make_scenarios.py --recipe <pantry-recipes server-id> [out-dir]
out-dir defaults to scenarios/generated/ in this repository (git-ignored).
"""
from __future__ import annotations

import pathlib
import re
import sys

import yaml

TOOLS = ["list_recipes", "get_recipe", "list_products", "find_product", "get_product", "plan_recipe",
         "plan_from_text", "plan_week", "get_product_origins", "rank_products_by_origin", "origin_triage",
         "submit_origin_evidence", "list_origin_submissions", "review_origin_submission", "pipeline_status"]
SLUG = "pantry"
ROOT = pathlib.Path(__file__).resolve().parent.parent
GENERATED = ROOT / "scenarios" / "generated"
PLACEHOLDER = "PANTRY_RECIPES_SERVER_ID"
SERVER_ID = re.compile(r"[A-Za-z0-9_-]+")


def gw(name: str) -> str:
    return f"{SLUG}-" + name.replace("_", "-")


def rename_text(s: str) -> str:
    for t in sorted(TOOLS, key=len, reverse=True):
        s = re.sub(rf"\b{t}\b", gw(t), s)
    return s


def rename_glob(g: str) -> str:
    return g if g == "*" else f"{SLUG}-" + g.replace("_", "-")


def walk(o):
    if isinstance(o, dict):
        return {k: walk(v) for k, v in o.items()}
    if isinstance(o, list):
        return [walk(v) for v in o]
    return rename_text(o) if isinstance(o, str) else o


def main(src: str, server_id: str, out: str) -> None:
    src_dir, out_dir = pathlib.Path(src), pathlib.Path(out)
    out_dir.mkdir(parents=True, exist_ok=True)
    for f in sorted(src_dir.glob("*.yaml")):
        d = yaml.safe_load(f.read_text())
        d["name"] = d["name"] + "-gateway"
        d["server"] = {"http": {"url": f"http://127.0.0.1:4444/servers/{server_id}/mcp",
                                "bearer_env": "CONTEXTFORGE_JWT"}}
        tools = d.get("tools") or {}
        for key in ("allow", "deny", "initial"):
            if tools.get(key):
                tools[key] = [rename_glob(g) for g in tools[key]]
        for k in ("goal", "role"):
            d[k] = rename_text(d[k])
        d["instructions"] = [rename_text(i) for i in d.get("instructions", [])]
        eo = d.get("expected_outcome", {})
        if eo.get("text"):
            eo["text"] = rename_text(eo["text"])
        if d.get("observers"):
            d["observers"] = walk(d["observers"])
        header = (f"# Generated by pantry-gateway/scripts/make_scenarios.py from {f.name}: the same scenario\n"
                  f"# reached through ContextForge's virtual server. Tool names/globs carry the gateway prefix;\n"
                  f"# needs CONTEXTFORGE_JWT in the environment. Regenerate after re-registering the server.\n")
        (out_dir / f.name).write_text(header + yaml.safe_dump(d, sort_keys=False, width=100, allow_unicode=True))
        print("wrote", out_dir / f.name)


def recipe(server_id: str, out: str | pathlib.Path) -> list[pathlib.Path]:
    """Fill the server id into this repository's gateway-only scenarios; returns the files written.

    A text substitution rather than a YAML round trip, so the scenario's comments survive; the
    result is parsed back to check that the id landed in ``server.http.url``.
    """
    if not SERVER_ID.fullmatch(server_id):
        sys.exit(f"not a server id: {server_id!r}")
    out_dir = pathlib.Path(out)
    out_dir.mkdir(parents=True, exist_ok=True)
    written = []
    for f in sorted((ROOT / "scenarios").glob("*.yaml")):
        text = f.read_text()
        if PLACEHOLDER not in text:
            sys.exit(f"{f}: no {PLACEHOLDER} placeholder to fill")
        filled = text.replace(PLACEHOLDER, server_id)
        url = (yaml.safe_load(filled).get("server") or {}).get("http", {}).get("url", "")
        if f"/servers/{server_id}/mcp" not in url:
            sys.exit(f"{f}: the placeholder is not in server.http.url ({url!r})")
        header = (f"# Generated by pantry-gateway/scripts/make_scenarios.py --recipe from scenarios/{f.name}:\n"
                  f"# the server id of this installation's 'pantry-recipes' virtual server filled in. Needs\n"
                  f"# CONTEXTFORGE_JWT in the environment. Regenerate after re-registering the server.\n")
        target = out_dir / f.name
        target.write_text(header + filled)
        written.append(target)
        print("wrote", target)
    return written


if __name__ == "__main__":
    argv = sys.argv[1:]
    if argv[:1] == ["--recipe"] and len(argv) in (2, 3):
        recipe(argv[1], argv[2] if len(argv) > 2 else GENERATED)
    elif argv[:1] != ["--recipe"] and len(argv) in (2, 3):
        main(argv[0], argv[1], argv[2] if len(argv) > 2 else str(GENERATED))
    else:
        sys.exit(__doc__)
