"""Derive gateway variants of mcp-sim's pantry scenarios.

ContextForge names a federated tool ``<gateway-slug>-<tool-with-dashes>`` (``find_product`` ->
``pantry-find-product``), so a scenario written for the direct server does not match through the
gateway. This rewrites tool names and globs, swaps the server block for the virtual server's MCP
endpoint, and leaves everything else (role, goal, expected outcome, observers) as it was.

Usage: make_scenarios.py <mcp-sim>/scenarios/pantry <server-id> [out-dir]
"""
from __future__ import annotations

import pathlib
import re
import sys

import yaml

TOOLS = ["list_recipes", "get_recipe", "list_products", "find_product", "get_product", "plan_recipe",
         "plan_from_text", "plan_week", "get_product_origins", "rank_products_by_origin", "origin_triage",
         "submit_origin_evidence", "list_origin_submissions", "review_origin_submission", "pipeline_status"]
SLUG = "pantry"


def gw(name: str) -> str:
    return f"{SLUG}-" + name.replace("_", "-")


def rename_text(s: str) -> str:
    for t in sorted(TOOLS, key=len, reverse=True):
        s = re.sub(rf"\b{t}\b", gw(t), s)
    return s


def rename_glob(g: str) -> str:
    return g if g == "*" else f"{SLUG}-" + g.replace("_", "-")


def walk(o):
    if isinstance(o, dict):
        return {k: walk(v) for k, v in o.items()}
    if isinstance(o, list):
        return [walk(v) for v in o]
    return rename_text(o) if isinstance(o, str) else o


def main(src: str, server_id: str, out: str) -> None:
    src_dir, out_dir = pathlib.Path(src), pathlib.Path(out)
    out_dir.mkdir(parents=True, exist_ok=True)
    for f in sorted(src_dir.glob("*.yaml")):
        d = yaml.safe_load(f.read_text())
        d["name"] = d["name"] + "-gateway"
        d["server"] = {"http": {"url": f"http://127.0.0.1:4444/servers/{server_id}/mcp",
                                "bearer_env": "CONTEXTFORGE_JWT"}}
        tools = d.get("tools") or {}
        for key in ("allow", "deny", "initial"):
            if tools.get(key):
                tools[key] = [rename_glob(g) for g in tools[key]]
        for k in ("goal", "role"):
            d[k] = rename_text(d[k])
        d["instructions"] = [rename_text(i) for i in d.get("instructions", [])]
        eo = d.get("expected_outcome", {})
        if eo.get("text"):
            eo["text"] = rename_text(eo["text"])
        if d.get("observers"):
            d["observers"] = walk(d["observers"])
        header = (f"# Generated by pantry-gateway/scripts/make_scenarios.py from {f.name}: the same scenario\n"
                  f"# reached through ContextForge's virtual server. Tool names/globs carry the gateway prefix;\n"
                  f"# needs CONTEXTFORGE_JWT in the environment. Regenerate after re-registering the server.\n")
        (out_dir / f.name).write_text(header + yaml.safe_dump(d, sort_keys=False, width=100, allow_unicode=True))
        print("wrote", out_dir / f.name)


if __name__ == "__main__":
    if len(sys.argv) < 3:
        sys.exit(__doc__)
    main(sys.argv[1], sys.argv[2], sys.argv[3] if len(sys.argv) > 3 else "scenarios/generated")
